### ISSUE TITLE
What was the python version used while the implementation was done? 

### ISSUE THREAD

**Issue by outisa** [adi3e08/Physics_Informed_Model_Based_RL#2]
I tried to reproduce the results with these versions of the requirements:
python      3.10.4
pytorch     2.3.0
tensorboard 2.16.2
pygame      2.5.2
numpy       1.26.4

I got a SystemError: unknown opcode and this is most likely caused by the different python version used while compiling the different robot.p codes. Could you perhaps add the used versions of the requirements at least for python and probably for pygame in the README.md?

Thanks in advance!

**Comment by ewanelwan** [comment]
You need to run the derive.py in each environment to generate the robot.p in each of them

**Comment by outisa** [comment]
Thanks for the fast response!

**Comment by ewanelwan** [comment]
@outisa 
You welcome
If you happened to run the code can you tell me how much time it took you on GPU and CPU

**Comment by outisa** [comment]
@ewanelwan
I tested the code only with reacher.
When I had 125 episodes, it took around 12 hours on GPU and around 14.5 Hours on CPU with similar results reported in the paper.

**Comment by adi3e08** [comment]
@outisa Thanks for sharing this issue. You are right, the robot.p files that I shared probably don't work for you due to a python version mismatch. I remember using Python 3.11, if I am not wrong. The exact version doesn't matter. Pick a recent version of Python. And like @ewanelwan has mentioned, run derive.py to generate your own robot.p files. That should mostly resolve your issue. Hence, I am marking this issue as closed.
