### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by ewanelwan** [adi3e08/Physics_Informed_Model_Based_RL#3]
I tried running the code for reacher environment, and it is supposed to be the easiest and least in actions and observations, it takes the same time on cpu and gpu
Is there some trick to have it train faster on GPU, or can you report the time it took to train for each environment?

Thank you

**Comment by adi3e08** [comment]
@ewanelwan For the model-based RL experiments (MBRL-DNN and MBRL-LNN), CPU and GPU take similar time, i. e., GPU doesn't offer any speed up. This is due to the hyperparameters I have chosen. For a different set of hyperparameters, GPU may offer speed up.

Meanwhile, for the baseline SAC experiments, GPU did speed things up.

**Comment by adi3e08** [comment]
@ewanelwan For the model-based RL experiments (MBRL-DNN and MBRL-LNN), CPU is faster than GPU. This is due to the hyperparameters I have chosen. For a different set of hyperparameters, GPU may offer speed up.

Meanwhile, for the baseline SAC experiments, GPU did speed things up.

Hope this resolves your issue. I am marking this issue as closed.

**Comment by ewanelwan** [comment]
@adi3e08 It took 4 days to run 100 episodes for MBRL-LNN for reacher  on gtx1070, is that reasonable?
Or Am I missing something?

**Comment by adi3e08** [comment]
My apologies. My previous comment was incorrect. It's been a while so I forgot some of the details.

For model-based RL experiments (MBRL-DNN and MBRL-LNN), CPU is faster than GPU, for the hyperparameters I have chosen. 

Reacher on CPU should take around 12 hours. GPU is probably much slower, so 4 days may be possible.

**Comment by adi3e08** [comment]
I have edited my previous comment to answer your question. Hope this resolves your issue.
